### ISSUE TITLE
test: function to cast a vote take too long to resolve

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx.js#122]
Currently on SX UI it take about 5 to 6 sec. for MetaMask to trigger when we cast a vote (using storage proof) there is even a moment for me when the browser freeze. We should run a test to be able to understand where time is spent ideally with a breakdown on how long each part of the function take and what may freeze the browser.

**Comment by Sekhmet** [comment]
`computeHashOnElements` is slow (function from starknet):
![Screenshot_20230120_110519](https://user-images.githubusercontent.com/1968722/213680850-c6b1d532-c72b-4601-b8a9-ee9a5baabe15.png)

This PR should bring in some improvements (currently in beta only): https://github.com/0xs34n/starknet.js/pull/399

**Comment by bonustrack** [comment]
Nice!

**Comment by Sekhmet** [comment]
@zzuziak the PR was merged to v5 branch which at the time I was testing had some things broken so I was unable to test it, but looks like there were some fixes on that branch pushed recently so I can retest.

**Comment by zzuziak** [comment]
Perfect, thanks!

**Comment by Sekhmet** [comment]
It's way faster with v5:
![image](https://user-images.githubusercontent.com/1968722/215553173-b7ec533e-fa98-421a-825c-67e4ab7823bd.png)

Comparison to v4:
![image](https://user-images.githubusercontent.com/1968722/215553635-b8d64b88-fda5-4afb-aace-08c88daa65f8.png)


Upgrade branch:  https://github.com/snapshot-labs/sx.js/pull/new/sekhmet/starknet-v5 (but I guess we will wait for v5 to become a stable release).

**Comment by bonustrack** [comment]
Wow awesomness

**Comment by bonustrack** [comment]
@Sekhmet Beta or not, it would be great to have this change in the UI before the StarkNet event

**Comment by zzuziak** [comment]
:tada:
