### ISSUE TITLE
Remove right padding on voter and proposer address

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx.js#92]
Currently the voter address or proposer address got padding like this:
https://github.com/snapshot-labs/sx.js/blob/eb40ed22833c2097d4288f842239991bb59e4d17/src/clients/ethereum-sig/index.ts#L130
This adding extra zeros on the addresses, we should try remove it

**Comment by Sekhmet** [comment]
`_signTypedData` will fail without it as it has `base32` type and without padding length is incorrect:
https://github.com/snapshot-labs/sx.js/blob/4269f2d9077318f75cc7f2b456e99aa4e57264bf/src/clients/ethereum-sig/types.ts#L7-L19

**Comment by bonustrack** [comment]
@Sekhmet This could be changed to `address` type.

@pscott @Orland0x Anything blocking us to remove the extra zeros padding on the addresses?

**Comment by Orland0x** [comment]
AFAIK we require the padding for the eip712 signature. @pscott will be able to confirm though.

**Comment by pscott** [comment]
This has already been updated in the SX test repo:
https://github.com/snapshot-labs/sx-core/blob/f9343c6fec721e6cb074bacd8506bdcc35cda97b/test/shared/types.ts#L25

Maybe we should delete this file in the SX repo and just use the `sx.js` to avoid this issue again?

**Comment by bonustrack** [comment]
@pscott So it should work without padding right? Agree about using sx.js on sx-core instead of duplicate code.

**Comment by pscott** [comment]
> @pscott So it should work without padding right? Agree about using sx.js on sx-core instead of duplicate code.

Yes it should. And this `type` simply won't work because everything has changed. You really need to use the types in https://github.com/snapshot-labs/sx-core/blob/f9343c6fec721e6cb074bacd8506bdcc35cda97b/test/shared/types.ts#L25 otherwise it simply won't work I think :) (unless you're using and old version of the authenticator! :))
