### ISSUE TITLE
Add proposal execution hash

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx.js#95]
When we create a proposal we should pass the execution hash, the hash is based on the transactions from the execution data. 

This is the function to generate the hash: https://github.com/snapshot-labs/sx.js/blob/878db990b3cdf3f9327a33d2da5d593909e7b59d/src/utils/encoding/execution-hash.ts#L44

This hash is used to verify the integrity of the execution on L1

**Comment by Sekhmet** [comment]
@bonustrack does it make sense to make clients accept executionHash? It's zodiac related so if different execution strategy is used it might be useless? If we don't have to worry about it, can `propose` just accept `txs: MetaTransaction[]`? This way consumer doesn't have to worry about details - they pass executor and list of transactions and internally in sx.js we find correct L1 relayer, build hash and execution params so it's all handled for the user.

**Comment by bonustrack** [comment]
@Sekhmet `executionHash` is not just for Zodiac, it's being used for StarkNet execution too and we use actually different format, we send the whole txs array in it. I think it make sense to move logic from UI to SX.js, similar than how you moved the logic for storage proof. Technically the format `txs: MetaTransaction[]` only work for execution on EVM but StarkNet execution I assume have a slightly different format, and I can imagine all sort of execution strategies that could use a different format even without txs, maybe it should use a different name than `txs`.
